parameters:
    locale: en
    date_format: '%env(DATE_FORMAT)%'
    month_date_format: '%env(MONTH_DATE_FORMAT)%'
    serialize_date_format: '%env(SERIALIZE_DATE_FORMAT)%'
    serialize_month_date_format: '%env(SERIALIZE_MONTH_DATE_FORMAT)%'
    regex_date: '%env(REGEX_DATE)%'
    regex_month_date: '%env(REGEX_MONTH_DATE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $dateFormat: '%date_format%'
            $monthDateFormat: '%month_date_format%'
            $serializeDateFormat: '%serialize_date_format%'
            $serializeMonthDateFormat: '%serialize_month_date_format%'
            $regexDate: '%regex_date%'
            $regexMonthDate: '%regex_month_date%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
